-- AlterTable
ALTER TABLE "Booking" ADD COLUMN     "endTime" TEXT NOT NULL DEFAULT '10:00',
ADD COLUMN     "peopleCount" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "startTime" TEXT NOT NULL DEFAULT '09:00',
ADD COLUMN     "totalPrice" DOUBLE PRECISION NOT NULL DEFAULT 0.0;

-- AlterTable
ALTER TABLE "GuideProfile" ADD COLUMN     "hourlyRate" DOUBLE PRECISION NOT NULL DEFAULT 20.0,
ALTER COLUMN "dailyRate" DROP NOT NULL;
